 <script src="https://www.paytabs.com/express/v4/paytabs-express-checkout.js"
            id="paytabs-express-checkout"
            data-secret-key="KPYFvAqrB2ZJsclE7FDoCbSmL525NJsxzrc42CwDFwn8JJNQoqf1B8nmdqs09VyJnKNpnk33QqbzaYqyoGA0OXn2oQ3xLBg9m4yK"
            data-merchant-id="10051714"
            data-url-redirect="http://brandxpend.com/pay"
            data-amount="{{$total}}"
            data-currency="AED"
            data-title="{{@Auth::user()->profile->first_name ?: 'No name'}}"
            data-product-names="{{$products}}"
            data-order-id="{{str_pad(mt_rand(1,99999999), 12, 0, STR_PAD_LEFT)}}"
            data-customer-phone-number="{{$mobile}}"
            data-customer-email-address="{{Auth::user()->email}}"
            data-customer-country-code="973"
            data-billing-full-address="{{ $address }}"
            data-billing-city="{{$city}}"
            data-billing-state="{{$state}}"
            data-billing-country="{{$country}}"
            data-billing-postal-code="{{$postcode}}"
            data-custom-css="a.PT_open_iframe {display:none !important}"
    >
    </script>